// Objective-C API for talking to github.com/Psiphon-Labs/psiphon-tunnel-core/AndroidLibrary/psi Go package.
//   gobind -lang=objc github.com/Psiphon-Labs/psiphon-tunnel-core/AndroidLibrary/psi
//
// File is generated by gobind. Do not edit.

#ifndef __GoPsi_H__
#define __GoPsi_H__

#include <Foundation/Foundation.h>

@protocol GoPsiPsiphonProvider;
@class GoPsiPsiphonProvider;

@protocol GoPsiPsiphonProvider
- (BOOL)bindToDevice:(int)fileDescriptor error:(NSError**)error;
- (NSString*)getPrimaryDnsServer;
- (NSString*)getSecondaryDnsServer;
- (int)hasNetworkConnectivity;
- (void)notice:(NSString*)noticeJSON;
@end

FOUNDATION_EXPORT BOOL GoPsiStart(NSString* configJson, NSString* embeddedServerEntryList, id<GoPsiPsiphonProvider> provider, BOOL useDeviceBinder, NSError** error);

FOUNDATION_EXPORT void GoPsiStop();

#endif
